# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ebc47cb875775fc0e6de750e2863e4faebba3e545ba497dab31858ea2f38a6d2d2dfcd47d324915826f509d0bbaba70faf57bc880808c2b1e86aef69bd1eb25

test:
  secret_key_base: e86e3b85c88e5d54e5b8a123e9ac8c2d4d389bde888e17a8af07d6a5cbcd466db74e078c57d27d70d8fc15fa47b1c30156db856abc37e298fe7c214b27e9890b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
